[theme]
primaryColor="#6B4F4F"
backgroundColor="#FAF8F4"
secondaryBackgroundColor="#6714B5"
textColor="#2E2E2E"
font = "Crafty Girls"
codeFont = "https://fonts.googleapis.com/css2?family=Crafty+Girls&display=swap" rel="stylesheet">"
